# Site settings
title: "Construyendo Mundos"
description: "Este es mi blog personal."
baseurl: ""
url: "monimarlo.github.io"

# Build settings
kramdown:
 input: GFM
 syntax_highlighter: rouge
permalink: pretty
gems: [jekyll-paginate]
paginate_path: "/page/:num"
paginate: 3
future: true
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]

# Links
links:
  - title: "blog"
    url: /
  - title: "sobre mí"
    url: /about
  - title: "rss"
    url: /feed.xml
